server:
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
      force: true
  log:
    filepath: logs/

spring:
  profiles:
    active: dev
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 600000
      keepalive-time: 300000
      connection-timeout: 30000
      validation-timeout: 5000
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

app:
  language:
    default: ko
  datetime:
    format: yyyy/MM/dd HH:mm

taskexecutor:
  corepoolsize: 4
  queuecapacity: 16
  maxpoolsize: 16

vapid:
  publicKey: BPVJyjxwClE_gDGyVWPFvs8OFR7QxrDRYg9c6i5bG6HFGNyjvpx3-NXeBTeNkagK7atP8NiVlUoUtglzYvrh38Y
  privateKey: fq5n1LYvwwUw2pTFauhmMnDT0YmjWyJkPzbV6wNb5GQ
  subject: mailto:support@gneworks.com
